# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: xenial
sudo: false
cache: packages
latex: true
pandoc_version: 2.5

deploy:
  Rscript -e 'mlr3book::render_mlr3book()'
