# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: bionic
sudo: false
cache: packages
latex: true
r_github_packages: mlr-org/mlr3book
pandoc_version: 2.7.3

script:
  - Rscript -e 'mlr3book::render_mlr3book()'

# deploy:
#   provider: pages
#   github_token: $GITHUB_TOKEN
#   local_dir: 'bookdown/_book'
#   skip_cleanup: true
#   keep_history: false
#   fqdn: mlr3book.mlr-org.com
#   on:
#     branch: master
