# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: xenial
sudo: false
cache: packages
latex: true
pandoc_version: 2.5

# temp fix
r_github_packages: r-lib/remotes#340

before_deploy:
  - R CMD INSTALL "${PKG_TARBALL}"
  - Rscript -e 'mlr3book::render_mlr3book()'

deploy:
  provider: pages
  local_dir: 'bookdown/book'
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: false
  on:
    branch: master
